services:
  cassandra:
    image: cassandra:5.0
    ports:
      - "9042:9042"
      - "9160:9160"
    # We enable password authentication that defaults to cassandra/cassandra superuser / pwd.
    # https://cassandra.apache.org/doc/stable/cassandra/operating/security.html#authentication
    command: >
      /bin/sh -c "echo 'authenticator: PasswordAuthenticator' >> /etc/cassandra/cassandra.yaml && docker-entrypoint.sh cassandra -f"
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  cassandra-net:
    driver: bridge
