service:
  extensions: [healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [kafka]
  telemetry:
    resource:
      service.name: jaeger_collector
    metrics:
      level: detailed

extensions:
  healthcheckv2:
    use_v2: true
    http:

receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

processors:
  batch:

exporters:
  kafka:
    brokers:
      - localhost:9092
    topic: "jaeger-spans"
    encoding: otlp_proto
