service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    trace_storage: some_storage
    trace_storage_archive: another_storage
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
      some_storage:
        cassandra:
          keyspace: "jaeger_v1_dc1"
          username: "cassandra"
          password: "cassandra"
      another_storage:
        cassandra:
          keyspace: "jaeger_v1_dc1"
          username: "cassandra"
          password: "cassandra"
receivers:
  otlp:
    protocols:
      grpc:
      http:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
